name: Automate Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'

jobs:
  on-success:
    needs: testing
    runs-on: ubuntu-latest
    if: ${{ always() && needs.testing.result == 'success' }}
    steps:
      - name: Notification Feishu
        uses: whatwewant/action-robot-feishu@v0.0.13
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          title: '✅ 自动化测试：${{ github.repository }}'
          text: |
            分支: ${{ github.ref }}
            提交信息: ${{ github.event.head_commit.message }}
            提交人: ${{ github.actor }}
            状态: 构建成功（https://github.com/${{ github.repository }}/actions/runs/${{ github.run.id }}）

  on-failure:
    needs: testing
    runs-on: ubuntu-latest
    if: ${{ always() && needs.testing.result == 'failure' }}
    steps:
      - name: Notification Feishu
        uses: whatwewant/action-robot-feishu@v0.0.13
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          title: '❌ 自动化测试：${{ github.repository }}'
          text: |
            分支: ${{ github.ref }}
            提交信息: ${{ github.event.head_commit.message }}
            提交人: ${{ github.actor }}
            状态: 构建失败（https://github.com/${{ github.repository }}/actions/runs/${{ github.run.id }}）

  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install
        run: ./install

      - name: Show Version
        run: |
          zmicro gvm -v
          export PATH=$(zmicro bin path):$PATH
          zgvm -v

     